language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - ./node_modules
if: branch = main
jobs:
    include:
        script:
            - echo 'Installing Deps!'
            - npm ci
            - npm run build
            - npm install firebase-tools -g
            - echo 'Deploy!!'
            - echo 'Deploy Success'
            - firebase deploy
    after_success:
        - firebase deploy --token "$FIREBASE_TOKEN"
