language: node_js
node_js:
  - "lts/*"
cache: npm

jobs:
  include:
    - stage: test
      script:
        - echo 'Deploy!!'
        - echo 'Installing Deps!'
        - npm ci
    - stage: build
      script:
        - npm run build
    - stage: deploy
      script:
        - npm install -g firebase-tools
        - firebase deploy --token "$FIREBASE_TOKEN" --only hosting
      skip_cleanup: true
