language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ./node_modules

jobs:
  include:
    script:
      - echo 'Installing Deps!'
      - npm ci
      - npm run build
      - npm install firebase-tools -g
      - echo 'Deploy!!'
    before_deploy:
      - echo 'Deploy Success'
      - firebase deploy
  deploy:
    provider: firebase
    token:
      secure: "$FIREBASE_TOKEN"
    skip_cleanup: true
