language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - ./node_modules
if: branch = main
jobs:
    include:
        - stage: install & build
        script:
            - echo 'Installing Deps!'
            - npm ci
            - echo 'Running Build'
            - npm run build
            - echo 'Installing firebase tools'
            - npm install firebase-tools -g
        - stage: test
        script:
            - echo 'Running Tests'
            - npm test
        - stage:
        script:
            - echo 'Deploying!'
            - firebase deploy --token "$FIREBASE_TOKEN"
