language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ./node_modules

jobs:
  include:
    - stage: test
    script:
      - echo 'Installing Deps!'
      - npm ci
      - npm run build
      - npm install firebase-tools -g
      - echo 'Deploy!!'
      - echo 'Deploy Success'
      - firebase deploy
    - stage: deploy
  after_success:
    - firebase deploy --token "$FIREBASE_TOKEN"
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
