language: node_js
node_js:
  - "lts/*"
cache: npm

jobs:
  include:
    - stage: test
      script:
        - echo 'Deploy!!'
        - echo 'Installing Deps!'
        - npm ci
    - stage: build
      script:
        - npm run build
    - stage: deploy
    deploy:
    provider: firebase
    token:
        secure: "$FIREBASE_TOKEN"
    project: "react-btns"
    skip_cleanup: true
