language: node_js
node_js:
  - "lts/*"
cache: npm

jobs:
  include:
    script:
      - echo 'Deploy!!'
      - echo 'Installing Deps!'
      - npm ci
      - npm run build
  deploy:
    provider: firebase
    token:
      secure: "$FIREBASE_TOKEN"
    project: "react-btns"
    skip_cleanup: true
